### PR TITLE
Normalize `x` in hex entities to lowercase

### PR DESCRIPTION
**Pull request by JordanMilne**
:eyeglasses: @spladug 

As it turns out, many XML parsers (souptest's included) *really* don't like uppercase `x`s there. `&#X3E;` == "invalid decimal value"!

Before the patch:

```python
In [5]: markdown_souptest("&#x3E;")
Out[5]: '<!-- SC_OFF --><div class="md"><p>&#x3E;</p>\n</div><!-- SC_ON -->'

In [6]: markdown_souptest("&#X3E;")
---------------------------------------------------------------------------
SoupSyntaxError: HAX: XML Parsing error: XMLSyntaxError(u'CharRef: invalid decimal value, line 297, column 39',)
```

### CODE REVIEW

**Comment by andre-d** [comment]
Who knew parsing valid XML entities had so many gotchas

**Comment by JordanMilne** [comment]
People who can actually stay awake while reading through the spec :cry:

**Comment by spladug** [comment]
:fish:

**Comment by JordanMilne** [comment]
049caf7912ed2f4ee7bcbc691ee78ed11df0db5b

**Pull request closed without merging**
